### ISSUE TITLE
Vouchers json editor

### ISSUE THREAD

**Issue by EagL3-GIT** [Tweetzy/Vouchers#13]
**Describe Feature**
Would be great to be able to edit vouchers and create them also in yml file, not just ingame cause for me ingame editor is time taker and its slow.

**Comment by Zybrodz** [comment]
its not slow if you get used to it

**Comment by MattDeWeerd** [comment]
@kiranhart I see this is assigned, is there any chance this could be implemented soon?
I am trying to make ~50 similar vouchers and it would be so much faster / easier if this was an option
