### ISSUE TITLE
Vouchers Cannot Be Sold in Shop; Locked to OP

### ISSUE THREAD

**Issue by TraipsingShadow** [Tweetzy/Vouchers#14]
**Describe the bug**
Vouchers cannot be accessed by anyone except the OP, rendering it irredeemable as an item in a shop.

It also cannot be thrown or given away once held.

**To Reproduce**
- Create a Voucher without permissions (any voucher)
- Obtain Voucher from menu
- Place obtained voucher into Villager/Chest/Shopkeeper
- Let a non-OP purchase the said item

**Expected behavior**
The non-OP player should be able to right-click the voucher to redeem the items and run the other commands. This does not happen. Once purchased, it cannot be redeemed by the said non-OP player.

**Server Information (please complete the following information):**
- Minecraft 1.19.2
- `paper-1.19.2-196.jar`
 3.3.0

**Comment by Zybrodz** [comment]
Please show me all the plugins you have used on your server
