### ISSUE TITLE
Commands aren't working

### ISSUE THREAD

**Issue by Zybrodz** [Tweetzy/Vouchers#15]
i set a command for a voucher
and it is
egive %player% netherite_block 81
in console it says 
[16:51:47 INFO]: Unknown command. Type "/help" for help.
i have not changed the config and i am not sure how to fix this problem.
Please help.

Zybrodz

**Comment by kiranhart** [comment]
does the command egive exist on your server?

**Comment by Zybrodz** [comment]
correct, it does exist

**Comment by Zybrodz** [comment]
i tried /give aswell but egive works exactly the same as /give, so doesnt really matter what i do

**Comment by kiranhart** [comment]
By any chance, do you have a chat colour plugin on your server?

**Comment by Zybrodz** [comment]
i do, sorry i took a while to respond i completely forgot this post existed

**Comment by Zybrodz** [comment]
ChatColor2 was the plugin
