### ISSUE TITLE
Give command not working?

### ISSUE THREAD

**Issue by Blu1040** [Tweetzy/Vouchers#21]
what exactly is the give command to give someone a voucher? because i tried the autofilled order and it didnt work and i tried a lot of different orders and it either did nothing at all or said player not online.. plz help :{

**Comment by Blu1040** [comment]
oh i found it out. I used the auto fill order but the voucher has to have no spaces in order for it to work i guess?

**Comment by kiranhart** [comment]
Yea, voucher ids shouldn't be created with spaces, the actual display names can be changed to include colors/spaces
