### ISSUE TITLE
spawner egg vouchers spawning mobs

### ISSUE THREAD

**Issue by scope404** [Tweetzy/Vouchers#23]
**Describe the bug**
Can use vouchers with spawner egg as it's item if used against a block will spawn a mob instead of using the voucher

**To Reproduce**
- make a voucher using spawner egg and use it against a block (I used shulker spawn egg)

**Expected behavior**
Not spawn a mob and voucher actually working.

**Screenshots**
![image](https://user-images.githubusercontent.com/70687963/217993314-03728d41-45df-428f-b6f1-360fc88957ce.png)

**Server Information (please complete the following information):**
- 1.19.3
- pufferfish
- 3.7.1

**Comment by kiranhart** [comment]
Was fixed in a previous update
