### ISSUE TITLE
Permission requirement button bug

### ISSUE THREAD

**Issue by BartosB13** [Tweetzy/Vouchers#29]
In the voucher editing options, after pressing the "Requires Permission" button, only the color of the glass changes. The description of this option does not change. It shows "True" all the time. I don't know if it's just a visual glitch or something more serious.

![bug](https://user-images.githubusercontent.com/89303317/228777064-d3ea4eb0-9638-4520-a870-3f9f4e86e39e.png)

**Comment by kiranhart** [comment]
Force close, should have been auto closed
