### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by craft2style** [Tweetzy/Vouchers#3]
Vouchers v1.8.20
mincraft versie 1.18.1

19.01 21:22:55 [Server] Server thread/WARN java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because the return value of "ca.tweetzy.vouchers.core.utils.nms.NBTEditor.getMethod(String)" is null
19.01 21:22:55 [Server] Server thread/WARN at ca.tweetzy.vouchers.core.utils.nms.NBTEditor.getCompound(NBTEditor.java:487)
19.01 21:22:55 [Server] Server thread/WARN at ca.tweetzy.vouchers.core.utils.nms.NBTEditor.getItemTag(NBTEditor.java:473)
19.01 21:22:55 [Server] Server thread/WARN at ca.tweetzy.vouchers.core.utils.nms.NBTEditor.getValue(NBTEditor.java:861)
19.01 21:22:55 [Server] Server thread/WARN at ca.tweetzy.vouchers.core.utils.nms.NBTEditor.contains(NBTEditor.java:1074)
19.01 21:22:55 [Server] Server thread/WARN at ca.tweetzy.vouchers.listener.PlayerListener.onRightClick(PlayerListener.java:76)
19.01 21:22:55 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19.01 21:22:55 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19.01 21:22:55 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.01 21:22:55 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471)
19.01 21:22:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:467)
19.01 21:22:55 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1586)
19.01 21:22:55 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
19.01 21:22:55 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
19.01 21:22:55 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
19.01 21:23:00 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
19.01 21:23:00 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kiranhart** [comment]
resolved in v3
