### ISSUE TITLE
Vouchers can't be droped when take from vouchers list

### ISSUE THREAD

**Issue by UnitedCraft** [Tweetzy/Vouchers#32]
**Describe the bug**
When You take a voucher from voucher list You can drop them by using Q key

**To Reproduce**
- take voucher from voucher list
- click Your drop key

**Expected behavior**
It can be droped like normal item

**Server Information (please complete the following information):**
- server version 1.19.4
- purpur
- 3.11.1

**Comment by ChesneyCorp** [comment]
Fixed, making PR soon.
