### ISSUE TITLE
Can't Drop Items 

### ISSUE THREAD

**Issue by K-r-u-z** [Tweetzy/Vouchers#38]
**Describe the bug**

Once I grab a voucher out of the /vouchers gui , I am unable to press 'Q' to drop the voucher. 

**To Reproduce**

_1)  Type /vouchers
2)  Click on "Vouchers Lists"
3)  Select one of your vouchers
4) Press 'Q' while holding voucher
5) Initially the voucher will drop
6) Pick up voucher and claim
7) Repeat steps 1-3
8) Press 'Q' while holding voucher and it refuses to drop. Just pops back in to inventory really fast._

**Expected behavior**

To drop the voucher on the ground.

**Server Information (please complete the following information):**

- Version: 1.19.4
- Paper.jar
- 3.13.0

**Comment by K-r-u-z** [comment]
I have identified the problem at hand—an unfortunate compatibility issue with a plugin named ViaRewind. Upon thorough testing with only these two plugins installed, I was able to successfully reproduce the issue. However, I am pleased to inform you that Vouchers continues to function seamlessly alongside ViaVersion and ViaBackwards.

**Comment by kiranhart** [comment]
Good to know, is it 100% confirmed to be caused by that plugin?

**Comment by K-r-u-z** [comment]
> 

After a few days of running, yes removing that plugin has resolved the issue and it has not happened again.
