### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by Turretedash7** [Tweetzy/Vouchers#39]
Hello there

Are we able to get the plugin update to the newest 1.20 version for paper 

As is seems the commands in the voucher gui will no longer work and player can no longer accept the voucher

**Comment by kiranhart** [comment]
Yea I’m just waiting on a third party library I use to get updated.

**Comment by Turretedash7** [comment]
Sweet no worries. Just wanted to add this in that all :)

**Comment by RHX0R3** [comment]
Hi there, what's the status on the update?
Which library is outdated?

**Comment by kiranhart** [comment]
> Hi there, what's the status on the update?
> 
> Which library is outdated?

Honestly no idea, I'm going to have to switch to NBTApi tbh

**Comment by kiranhart** [comment]
Update Posted
