### ISSUE TITLE
i Need help it keeps on crashing idk why

### ISSUE THREAD

**Issue by PvpGods** [Tweetzy/Vouchers#4]
Hello There idk why but the Plugin keeps on crashing everytime i start the server it worked the other day but when i restarted the server it just crashes i will give you the Error log to see if you can figure out whats wrong cuz i can't Thanks
[error (2).log](https://github.com/Tweetzy/Vouchers/files/8086760/error.2.log)
!

**Comment by kiranhart** [comment]
resolved in v3
