### ISSUE TITLE
Console error - "ItemStack can't be null/air/amount of 0!"

### ISSUE THREAD

**Issue by RHX0R3** [Tweetzy/Vouchers#40]
**Describe the bug**

After the NullPointerException the console gets spammed with one error.
It affects the performance of the server enormously.

**Server Information**

- Paper version 1.20.1, Build 31
- Vouchers 3.14.0

**Console error**

https://hastebin.com/share/dunanexuje.swift

**Plugins involved (probably)**

- IllegalStack version 2.8.2 [click](https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/)

It deleted the book(and quill) item, when I clicked the item in GUI, when editing the description/lore of the voucher item.
Actions taken: [click](https://hastebin.com/share/locafamemo.sql)

**Solution**

Maybe add a check, by going through the GUI or the database itself, and automatically change those empty ItemStacks to an alternative, like STONE or smt.

**Comment by RHX0R3** [comment]
**Additional information**

Even with my backup, it is not possible to not make that error occur.
I can't quite wrap my head around, why this is happening. I even deactivated the deletion option in IllegalStacks for books with content not matching the charset.

But at this point, I don't think, that it has anything to do anymore :(

Here is my full server log: https://hastebin.com/share/etexonedas.wasm


Nevertheless, it would certainly not be wrong to include a check if an ItemStack is set to _null/air/0_, to replace it with the number 1 etc.

I know this seems to be a very unusual issue, but I wanted to report it anyway because other users might be having this issue too.

Best regards,
X0R3

**Comment by kiranhart** [comment]
Resolved - see update 3.15.0
