### ISSUE TITLE
Can't redeem vouchers in offhand

### ISSUE THREAD

**Issue by fucksophie** [Tweetzy/Vouchers#43]
**Describe the bug**
When a voucher is in a offhand, you cannot use it. Offhand vouchers should be supported.

**To Reproduce**

1. Create a simple voucher
2. Put it in your offhand
3. Rightclick, doesn't function

**Expected behavior**
1. Put voucher in your offhand
2. Rightclick
3. Voucher gets removed & used

**Why is this useful?**
Very useful to dynamically apply enchantments through /enchant or NBT editing to a player
Like sharpness 20 and stuff, to their currently held item

**Server Information (please complete the following information):**

- Paper e8bec64 (1.20.1)
- Vouchers 3.3.0

**Comment by ChesneyCorp** [comment]
Fixed, making PR soon.
